# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sticker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sticker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsticker.proto\x12\x07sticker\"\x1c\n\x0eStickerRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\x0fStickerResponse\x12\x0b\n\x03url\x18\x01 \x01(\t2Q\n\x0eStickerService\x12?\n\nGetSticker\x12\x17.sticker.StickerRequest\x1a\x18.sticker.StickerResponseB4Z2github.com/LucasCodo/projeto-1-SOA/proto;stickerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sticker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/LucasCodo/projeto-1-SOA/proto;stickerpb'
  _globals['_STICKERREQUEST']._serialized_start=26
  _globals['_STICKERREQUEST']._serialized_end=54
  _globals['_STICKERRESPONSE']._serialized_start=56
  _globals['_STICKERRESPONSE']._serialized_end=86
  _globals['_STICKERSERVICE']._serialized_start=88
  _globals['_STICKERSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
