# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sticker_pb2 as sticker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sticker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StickerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSticker = channel.unary_unary(
                '/sticker.StickerService/GetSticker',
                request_serializer=sticker__pb2.StickerRequest.SerializeToString,
                response_deserializer=sticker__pb2.StickerResponse.FromString,
                _registered_method=True)


class StickerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSticker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StickerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSticker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSticker,
                    request_deserializer=sticker__pb2.StickerRequest.FromString,
                    response_serializer=sticker__pb2.StickerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sticker.StickerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sticker.StickerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StickerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSticker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sticker.StickerService/GetSticker',
            sticker__pb2.StickerRequest.SerializeToString,
            sticker__pb2.StickerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
