// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: sticker.proto

package stickerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerRequest) Reset() {
	*x = StickerRequest{}
	mi := &file_sticker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerRequest) ProtoMessage() {}

func (x *StickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sticker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerRequest.ProtoReflect.Descriptor instead.
func (*StickerRequest) Descriptor() ([]byte, []int) {
	return file_sticker_proto_rawDescGZIP(), []int{0}
}

func (x *StickerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StickerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerResponse) Reset() {
	*x = StickerResponse{}
	mi := &file_sticker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerResponse) ProtoMessage() {}

func (x *StickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sticker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerResponse.ProtoReflect.Descriptor instead.
func (*StickerResponse) Descriptor() ([]byte, []int) {
	return file_sticker_proto_rawDescGZIP(), []int{1}
}

func (x *StickerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_sticker_proto protoreflect.FileDescriptor

const file_sticker_proto_rawDesc = "" +
	"\n" +
	"\rsticker.proto\x12\asticker\" \n" +
	"\x0eStickerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x0fStickerResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2Q\n" +
	"\x0eStickerService\x12?\n" +
	"\n" +
	"GetSticker\x12\x17.sticker.StickerRequest\x1a\x18.sticker.StickerResponseB4Z2github.com/LucasCodo/projeto-1-SOA/proto;stickerpbb\x06proto3"

var (
	file_sticker_proto_rawDescOnce sync.Once
	file_sticker_proto_rawDescData []byte
)

func file_sticker_proto_rawDescGZIP() []byte {
	file_sticker_proto_rawDescOnce.Do(func() {
		file_sticker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sticker_proto_rawDesc), len(file_sticker_proto_rawDesc)))
	})
	return file_sticker_proto_rawDescData
}

var file_sticker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sticker_proto_goTypes = []any{
	(*StickerRequest)(nil),  // 0: sticker.StickerRequest
	(*StickerResponse)(nil), // 1: sticker.StickerResponse
}
var file_sticker_proto_depIdxs = []int32{
	0, // 0: sticker.StickerService.GetSticker:input_type -> sticker.StickerRequest
	1, // 1: sticker.StickerService.GetSticker:output_type -> sticker.StickerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sticker_proto_init() }
func file_sticker_proto_init() {
	if File_sticker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sticker_proto_rawDesc), len(file_sticker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sticker_proto_goTypes,
		DependencyIndexes: file_sticker_proto_depIdxs,
		MessageInfos:      file_sticker_proto_msgTypes,
	}.Build()
	File_sticker_proto = out.File
	file_sticker_proto_goTypes = nil
	file_sticker_proto_depIdxs = nil
}
