// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: sticker.proto

package stickerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StickerService_GetSticker_FullMethodName = "/sticker.StickerService/GetSticker"
)

// StickerServiceClient is the client API for StickerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StickerServiceClient interface {
	GetSticker(ctx context.Context, in *StickerRequest, opts ...grpc.CallOption) (*StickerResponse, error)
}

type stickerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStickerServiceClient(cc grpc.ClientConnInterface) StickerServiceClient {
	return &stickerServiceClient{cc}
}

func (c *stickerServiceClient) GetSticker(ctx context.Context, in *StickerRequest, opts ...grpc.CallOption) (*StickerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StickerResponse)
	err := c.cc.Invoke(ctx, StickerService_GetSticker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StickerServiceServer is the server API for StickerService service.
// All implementations must embed UnimplementedStickerServiceServer
// for forward compatibility.
type StickerServiceServer interface {
	GetSticker(context.Context, *StickerRequest) (*StickerResponse, error)
	mustEmbedUnimplementedStickerServiceServer()
}

// UnimplementedStickerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStickerServiceServer struct{}

func (UnimplementedStickerServiceServer) GetSticker(context.Context, *StickerRequest) (*StickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSticker not implemented")
}
func (UnimplementedStickerServiceServer) mustEmbedUnimplementedStickerServiceServer() {}
func (UnimplementedStickerServiceServer) testEmbeddedByValue()                        {}

// UnsafeStickerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StickerServiceServer will
// result in compilation errors.
type UnsafeStickerServiceServer interface {
	mustEmbedUnimplementedStickerServiceServer()
}

func RegisterStickerServiceServer(s grpc.ServiceRegistrar, srv StickerServiceServer) {
	// If the following call pancis, it indicates UnimplementedStickerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StickerService_ServiceDesc, srv)
}

func _StickerService_GetSticker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).GetSticker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_GetSticker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).GetSticker(ctx, req.(*StickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StickerService_ServiceDesc is the grpc.ServiceDesc for StickerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StickerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sticker.StickerService",
	HandlerType: (*StickerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSticker",
			Handler:    _StickerService_GetSticker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sticker.proto",
}
